Feast:
  Material:
    373:
      durabilidade: 16460
      quantidade: 3
    373:
      durabilidade: 16420
      quantidade: 3
    373:
      durabilidade: 16418
      quantidade: 3
    373:
      durabilidade: 16420
      quantidade: 3
    373:
      durabilidade: 16426
      quantidade: 3
    261:
      durabilidade: 0
      quantidade: 1
    262:
      durabilidade: 0
      quantidade: 6
    282:
      durabilidade: 0
      quantidade: 9
    384:
      durabilidade: 0
      quantidade: 3
    298:
      durabilidade: 0
      quantidade: 1
    299:
      durabilidade: 0
      quantidade: 1
    300:
      durabilidade: 0
      quantidade: 1
    301:
      durabilidade: 0
      quantidade: 1